In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df=pd.read_csv('../input/marriage-status/marital status.csv')

In [3]:
df.head(5)

   age  status
0   21     0.0
1   33     1.0
2   24     0.0
3   28     1.0
4   17     0.0

In [4]:
df.isnull().sum()

age       0
status    1
dtype: int64

In [5]:
##Handling Nan using Median

median=df['status'].median()

In [6]:
df.status=df.status.fillna(median)

In [7]:
df.isnull().sum()

age       0
status    0
dtype: int64

In [8]:
##Count Value (0 and 1)

df['status'].value_counts()

0.0    11
1.0     9
Name: status, dtype: int64

In [9]:
##Split the X and y 

x=df[['age']]

In [10]:
y=df['status']

In [11]:
##Take Data Size

from sklearn.model_selection import train_test_split

In [12]:
##Take Data Size

X_train, X_test, y_train, y_test = train_test_split(
                      x, y, test_size=0.33, random_state=42)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
Lg=LogisticRegression()

In [17]:
Lg.fit(X_train,y_train)

LogisticRegression()

In [19]:
Lg.predict(X_test)

array([0., 0., 1., 1., 1., 1., 0.])

In [22]:
X_test

    age
0    21
17   18
15   29
1    33
8    29
5    33
11   20

In [23]:
df

    age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   22     0.0
13   24     0.0
14   34     1.0
15   29     1.0
16   16     0.0
17   18     0.0
18   26     1.0
19   25     1.0

In [25]:
Accuracy=Lg.score(X_test,y_test)

In [ ]:
##Accuracy Print

print("The Accuracy is ", Accuracy)